<a href="https://colab.research.google.com/github/HurtovaAlina/ITStep-AI/blob/superwised_learning/home_work_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль pandas

In [2]:
import pandas as pd

# Інформація про дані
Зібрано дані продажу техніки в різних магазинах.
* OrderDate -- дата замовлення
* Region    -- регіон де розміщено магазин
* Manager   -- ім'я менеджера
* SalesMan  -- ім'я продавця
* Item      -- тип товару
* Units     -- кількість купленого товару
* Unit_price -- ціна за штуку
* Sale_amt   -- загальна вартість покупки

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/sales_data.csv", index_col="Unnamed: 0")

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [4]:
df

,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.00,1198.000,113810.00
1,2018-01-23,Central,Hermann,Shelli,Home Theater,50.00,500.000,25000.00
2,2018-02-09,Central,Hermann,Luis,Television,36.00,1198.000,43128.00
3,2018-02-26,Central,Timothy,David,Cell Phone,27.00,225.000,6075.00
4,2018-03-15,West,Timothy,Stephen,Television,56.00,1198.000,67088.00
5,2018-04-01,East,Martha,Alexander,Home Theater,60.00,500.000,30000.00
6,2018-04-18,Central,Martha,Steven,Television,75.00,1198.000,89850.00
7,2018-05-05,Central,Hermann,Luis,Television,90.00,1198.000,107820.00
8,2018-05-22,West,Douglas,Michael,Television,32.00,1198.000,38336.00
9,2018-06-08,East,Martha,Alexander,Home Theater,60.00,500.000,30000.00
10,2018-06-25,Central,Hermann,Sigal,Television,90.00,1198.000,107820.00
11,2018-07-12,East,Martha,Diana,Home Theater,29.00,500.000,14500.00
12,2018-07-29,East,Douglas,Karen,Home Theater,81.00,500.000,40500.00
13,2018-08-15,East,Martha,Alexander,Television,35.00,1198.000,41930.00
14,2018-09-01,Central,Douglas,John,Desk,2.00,125.000,250.00
15,2018-09-18,East,Martha,Alexander,Video Games,16.00,58.500,936.00
16,2018-10-05,Central,Hermann,Sigal,Home Theater,28.00,500.000,14000.00
17,2018-10-22,East,Martha,Alexander,Cell Phone,64.00,225.000,14400.00
18,2018-11-08,East,Douglas,Karen,Cell Phone,15.00,225.000,3375.00
19,2018-11-25,Central,Hermann,Shelli,Video Games,96.00,58.500,5616.00
20,2018-12-12,Central,Douglas,John,Television,67.00,1198.000,80266.00
21,2018-12-29,East,Douglas,Karen,Video Games,74.00,58.500,4329.00
22,2019-01-15,Central,Timothy,David,Home Theater,46.00,500.000,23000.00
23,2019-02-01,Central,Douglas,John,Home Theater,87.00,500.000,43500.00
24,2019-02-18,East,Martha,Alexander,Home Theater,4.00,500.000,2000.00
25,2019-03-07,West,Timothy,Stephen,Home Theater,7.00,500.000,3500.00
26,2019-03-24,Central,Hermann,Luis,Video Games,50.00,58.500,2925.00
27,2019-04-10,Central,Martha,Steven,Television,66.00,1198.000,79068.00
28,2019-04-27,East,Martha,Diana,Cell Phone,96.00,225.000,21600.00
29,2019-05-14,Central,Timothy,David,Television,53.00,1198.000,63494.00
30,2019-05-31,Central,Timothy,David,Home Theater,80.00,500.000,40000.00
31,2019-06-17,Central,Hermann,Shelli,Desk,5.00,125.000,625.00
32,2019-07-04,East,Martha,Alexander,Video Games,62.00,58.500,3627.00
33,2019-07-21,Central,Hermann,Sigal,Video Games,55.00,58.500,3217.50
34,2019-08-07,Central,Hermann,Shelli,Video Games,42.00,58.500,2457.00
35,2019-08-24,West,Timothy,Stephen,Desk,3.00,125.000,375.00
36,2019-09-10,Central,Timothy,David,Television,7.00,1198.000,8386.00
37,2019-09-27,West,Timothy,Stephen,Cell Phone,76.00,225.000,17100.00
38,2019-10-14,West,Douglas,Michael,Home Theater,57.00,500.000,28500.00
39,2019-10-31,Central,Martha,Steven,Television,14.00,1198.000,16772.00
40,2019-11-17,Central,Hermann,Luis,Home Theater,11.00,500.000,5500.00
41,2019-12-04,Central,Hermann,Luis,Home Theater,94.00,500.000,47000.00
42,2019-12-21,Central,Martha,Steven,Home Theater,28.00,500.000,14000.00
43,NaN,NaN,NaN,NaN,NaN,278.00,1125.000,62550.00
44,NaN,NaN,NaN,NaN,NaN,34.75,140.625,7818.75

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 0 to 44
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderDate   43 non-null     object
 1   Region      43 non-null     object
 2   Manager     43 non-null     object
 3   SalesMan    43 non-null     object
 4   Item        43 non-null     object
 5   Units       45 non-null     float64
 6   Unit_price  45 non-null     float64
 7   Sale_amt    45 non-null     float64
dtypes: float64(3), object(5)
memory usage: 4.2+ KB

In [7]:
df.shape

(45, 8)

In [8]:
df.dtypes

OrderDate      object
Region         object
Manager        object
SalesMan       object
Item           object
Units         float64
Unit_price    float64
Sale_amt      float64
dtype: object

# Завдання 2

Перейменуйте стовпчики так, щоб назви містили літери нижнього регістру

In [13]:
df.columns = df.columns.str.lower()
new_table_with_lower_case = df
new_table_with_lower_case

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.00,1198.000,113810.00
1,2018-01-23,Central,Hermann,Shelli,Home Theater,50.00,500.000,25000.00
2,2018-02-09,Central,Hermann,Luis,Television,36.00,1198.000,43128.00
3,2018-02-26,Central,Timothy,David,Cell Phone,27.00,225.000,6075.00
4,2018-03-15,West,Timothy,Stephen,Television,56.00,1198.000,67088.00
5,2018-04-01,East,Martha,Alexander,Home Theater,60.00,500.000,30000.00
6,2018-04-18,Central,Martha,Steven,Television,75.00,1198.000,89850.00
7,2018-05-05,Central,Hermann,Luis,Television,90.00,1198.000,107820.00
8,2018-05-22,West,Douglas,Michael,Television,32.00,1198.000,38336.00
9,2018-06-08,East,Martha,Alexander,Home Theater,60.00,500.000,30000.00
10,2018-06-25,Central,Hermann,Sigal,Television,90.00,1198.000,107820.00
11,2018-07-12,East,Martha,Diana,Home Theater,29.00,500.000,14500.00
12,2018-07-29,East,Douglas,Karen,Home Theater,81.00,500.000,40500.00
13,2018-08-15,East,Martha,Alexander,Television,35.00,1198.000,41930.00
14,2018-09-01,Central,Douglas,John,Desk,2.00,125.000,250.00
15,2018-09-18,East,Martha,Alexander,Video Games,16.00,58.500,936.00
16,2018-10-05,Central,Hermann,Sigal,Home Theater,28.00,500.000,14000.00
17,2018-10-22,East,Martha,Alexander,Cell Phone,64.00,225.000,14400.00
18,2018-11-08,East,Douglas,Karen,Cell Phone,15.00,225.000,3375.00
19,2018-11-25,Central,Hermann,Shelli,Video Games,96.00,58.500,5616.00
20,2018-12-12,Central,Douglas,John,Television,67.00,1198.000,80266.00
21,2018-12-29,East,Douglas,Karen,Video Games,74.00,58.500,4329.00
22,2019-01-15,Central,Timothy,David,Home Theater,46.00,500.000,23000.00
23,2019-02-01,Central,Douglas,John,Home Theater,87.00,500.000,43500.00
24,2019-02-18,East,Martha,Alexander,Home Theater,4.00,500.000,2000.00
25,2019-03-07,West,Timothy,Stephen,Home Theater,7.00,500.000,3500.00
26,2019-03-24,Central,Hermann,Luis,Video Games,50.00,58.500,2925.00
27,2019-04-10,Central,Martha,Steven,Television,66.00,1198.000,79068.00
28,2019-04-27,East,Martha,Diana,Cell Phone,96.00,225.000,21600.00
29,2019-05-14,Central,Timothy,David,Television,53.00,1198.000,63494.00
30,2019-05-31,Central,Timothy,David,Home Theater,80.00,500.000,40000.00
31,2019-06-17,Central,Hermann,Shelli,Desk,5.00,125.000,625.00
32,2019-07-04,East,Martha,Alexander,Video Games,62.00,58.500,3627.00
33,2019-07-21,Central,Hermann,Sigal,Video Games,55.00,58.500,3217.50
34,2019-08-07,Central,Hermann,Shelli,Video Games,42.00,58.500,2457.00
35,2019-08-24,West,Timothy,Stephen,Desk,3.00,125.000,375.00
36,2019-09-10,Central,Timothy,David,Television,7.00,1198.000,8386.00
37,2019-09-27,West,Timothy,Stephen,Cell Phone,76.00,225.000,17100.00
38,2019-10-14,West,Douglas,Michael,Home Theater,57.00,500.000,28500.00
39,2019-10-31,Central,Martha,Steven,Television,14.00,1198.000,16772.00
40,2019-11-17,Central,Hermann,Luis,Home Theater,11.00,500.000,5500.00
41,2019-12-04,Central,Hermann,Luis,Home Theater,94.00,500.000,47000.00
42,2019-12-21,Central,Martha,Steven,Home Theater,28.00,500.000,14000.00
43,NaN,NaN,NaN,NaN,NaN,278.00,1125.000,62550.00
44,NaN,NaN,NaN,NaN,NaN,34.75,140.625,7818.75

# Завдання 3
Виведіть дані про купівлі телевізорів та телефонів

In [16]:
mask_tv = new_table_with_lower_case['item'] == 'Television'
new_table_with_lower_case[mask_tv]

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
2,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
4,2018-03-15,West,Timothy,Stephen,Television,56.0,1198.0,67088.0
6,2018-04-18,Central,Martha,Steven,Television,75.0,1198.0,89850.0
7,2018-05-05,Central,Hermann,Luis,Television,90.0,1198.0,107820.0
8,2018-05-22,West,Douglas,Michael,Television,32.0,1198.0,38336.0
10,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
13,2018-08-15,East,Martha,Alexander,Television,35.0,1198.0,41930.0
20,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
27,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
29,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
36,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
39,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0

In [23]:
new_table_with_lower_case[mask_tv].count()

orderdate     13
region        13
manager       13
salesman      13
item          13
units         13
unit_price    13
sale_amt      13
dtype: int64

In [17]:
mask_phone = new_table_with_lower_case['item'] == 'Cell Phone'
new_table_with_lower_case[mask_phone]

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt
3,2018-02-26,Central,Timothy,David,Cell Phone,27.0,225.0,6075.0
17,2018-10-22,East,Martha,Alexander,Cell Phone,64.0,225.0,14400.0
18,2018-11-08,East,Douglas,Karen,Cell Phone,15.0,225.0,3375.0
28,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
37,2019-09-27,West,Timothy,Stephen,Cell Phone,76.0,225.0,17100.0

In [24]:
new_table_with_lower_case[mask_phone].count()

orderdate     5
region        5
manager       5
salesman      5
item          5
units         5
unit_price    5
sale_amt      5
dtype: int64

In [21]:
total = mask_tv | mask_phone
total

0      True
1     False
2      True
3      True
4      True
5     False
6      True
7      True
8      True
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16    False
17     True
18     True
19    False
20     True
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28     True
29     True
30    False
31    False
32    False
33    False
34    False
35    False
36     True
37     True
38    False
39     True
40    False
41    False
42    False
43    False
44    False
Name: item, dtype: bool

In [22]:
new_table_with_lower_case[total]

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
2,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
3,2018-02-26,Central,Timothy,David,Cell Phone,27.0,225.0,6075.0
4,2018-03-15,West,Timothy,Stephen,Television,56.0,1198.0,67088.0
6,2018-04-18,Central,Martha,Steven,Television,75.0,1198.0,89850.0
7,2018-05-05,Central,Hermann,Luis,Television,90.0,1198.0,107820.0
8,2018-05-22,West,Douglas,Michael,Television,32.0,1198.0,38336.0
10,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
13,2018-08-15,East,Martha,Alexander,Television,35.0,1198.0,41930.0
17,2018-10-22,East,Martha,Alexander,Cell Phone,64.0,225.0,14400.0
18,2018-11-08,East,Douglas,Karen,Cell Phone,15.0,225.0,3375.0
20,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
27,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
28,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
29,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
36,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
37,2019-09-27,West,Timothy,Stephen,Cell Phone,76.0,225.0,17100.0
39,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0

# Завдання 4
Яка загальна виручка у продавця Luis?

In [32]:
sales_by_salesman = new_table_with_lower_case.groupby(by='salesman')['sale_amt'].sum()
sales_by_salesman

salesman
Alexander    236703.0
David        140955.0
Diana         36100.0
John         124016.0
Karen         48204.0
Luis         206373.0
Michael       66836.0
Shelli        33698.0
Sigal        125037.5
Stephen       88063.0
Steven       199690.0
Name: sale_amt, dtype: float64

In [35]:
float(sales_by_salesman['Luis'])

206373.0

# Завдання 5

Скільки і якого товару було продано?

див groupby(),

In [36]:
sales_by_item = new_table_with_lower_case.groupby(by='item')['units'].sum()
sales_by_item

item
Cell Phone      278.0
Desk             10.0
Home Theater    722.0
Television      716.0
Video Games     395.0
Name: units, dtype: float64

# Завдання 6
Перевірте чи правильно розраховано загальну вартість покупки. Виведіть ті рядки де є помилка. Виправте дані в таблиці

In [39]:
new_table_with_lower_case['total_calculation'] =  new_table_with_lower_case['unit_price'] * df['units']
table_with_calc = new_table_with_lower_case
table_with_calc

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt,total_calculation
0,2018-01-06,East,Martha,Alexander,Television,95.00,1198.000,113810.00,113810.00000
1,2018-01-23,Central,Hermann,Shelli,Home Theater,50.00,500.000,25000.00,25000.00000
2,2018-02-09,Central,Hermann,Luis,Television,36.00,1198.000,43128.00,43128.00000
3,2018-02-26,Central,Timothy,David,Cell Phone,27.00,225.000,6075.00,6075.00000
4,2018-03-15,West,Timothy,Stephen,Television,56.00,1198.000,67088.00,67088.00000
5,2018-04-01,East,Martha,Alexander,Home Theater,60.00,500.000,30000.00,30000.00000
6,2018-04-18,Central,Martha,Steven,Television,75.00,1198.000,89850.00,89850.00000
7,2018-05-05,Central,Hermann,Luis,Television,90.00,1198.000,107820.00,107820.00000
8,2018-05-22,West,Douglas,Michael,Television,32.00,1198.000,38336.00,38336.00000
9,2018-06-08,East,Martha,Alexander,Home Theater,60.00,500.000,30000.00,30000.00000
10,2018-06-25,Central,Hermann,Sigal,Television,90.00,1198.000,107820.00,107820.00000
11,2018-07-12,East,Martha,Diana,Home Theater,29.00,500.000,14500.00,14500.00000
12,2018-07-29,East,Douglas,Karen,Home Theater,81.00,500.000,40500.00,40500.00000
13,2018-08-15,East,Martha,Alexander,Television,35.00,1198.000,41930.00,41930.00000
14,2018-09-01,Central,Douglas,John,Desk,2.00,125.000,250.00,250.00000
15,2018-09-18,East,Martha,Alexander,Video Games,16.00,58.500,936.00,936.00000
16,2018-10-05,Central,Hermann,Sigal,Home Theater,28.00,500.000,14000.00,14000.00000
17,2018-10-22,East,Martha,Alexander,Cell Phone,64.00,225.000,14400.00,14400.00000
18,2018-11-08,East,Douglas,Karen,Cell Phone,15.00,225.000,3375.00,3375.00000
19,2018-11-25,Central,Hermann,Shelli,Video Games,96.00,58.500,5616.00,5616.00000
20,2018-12-12,Central,Douglas,John,Television,67.00,1198.000,80266.00,80266.00000
21,2018-12-29,East,Douglas,Karen,Video Games,74.00,58.500,4329.00,4329.00000
22,2019-01-15,Central,Timothy,David,Home Theater,46.00,500.000,23000.00,23000.00000
23,2019-02-01,Central,Douglas,John,Home Theater,87.00,500.000,43500.00,43500.00000
24,2019-02-18,East,Martha,Alexander,Home Theater,4.00,500.000,2000.00,2000.00000
25,2019-03-07,West,Timothy,Stephen,Home Theater,7.00,500.000,3500.00,3500.00000
26,2019-03-24,Central,Hermann,Luis,Video Games,50.00,58.500,2925.00,2925.00000
27,2019-04-10,Central,Martha,Steven,Television,66.00,1198.000,79068.00,79068.00000
28,2019-04-27,East,Martha,Diana,Cell Phone,96.00,225.000,21600.00,21600.00000
29,2019-05-14,Central,Timothy,David,Television,53.00,1198.000,63494.00,63494.00000
30,2019-05-31,Central,Timothy,David,Home Theater,80.00,500.000,40000.00,40000.00000
31,2019-06-17,Central,Hermann,Shelli,Desk,5.00,125.000,625.00,625.00000
32,2019-07-04,East,Martha,Alexander,Video Games,62.00,58.500,3627.00,3627.00000
33,2019-07-21,Central,Hermann,Sigal,Video Games,55.00,58.500,3217.50,3217.50000
34,2019-08-07,Central,Hermann,Shelli,Video Games,42.00,58.500,2457.00,2457.00000
35,2019-08-24,West,Timothy,Stephen,Desk,3.00,125.000,375.00,375.00000
36,2019-09-10,Central,Timothy,David,Television,7.00,1198.000,8386.00,8386.00000
37,2019-09-27,West,Timothy,Stephen,Cell Phone,76.00,225.000,17100.00,17100.00000
38,2019-10-14,West,Douglas,Michael,Home Theater,57.00,500.000,28500.00,28500.00000
39,2019-10-31,Central,Martha,Steven,Television,14.00,1198.000,16772.00,16772.00000
40,2019-11-17,Central,Hermann,Luis,Home Theater,11.00,500.000,5500.00,5500.00000
41,2019-12-04,Central,Hermann,Luis,Home Theater,94.00,500.000,47000.00,47000.00000
42,2019-12-21,Central,Martha,Steven,Home Theater,28.00,500.000,14000.00,14000.00000
43,NaN,NaN,NaN,NaN,NaN,278.00,1125.000,62550.00,312750.00000
44,NaN,NaN,NaN,NaN,NaN,34.75,140.625,7818.75,4886.71875

In [41]:
mask_wrong = table_with_calc['sale_amt'] != table_with_calc['total_calculation']
mask_wrong

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43     True
44     True
dtype: bool

In [43]:
table_with_calc[mask_wrong]

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt,total_calculation
43,NaN,NaN,NaN,NaN,NaN,278.00,1125.000,62550.00,312750.00000
44,NaN,NaN,NaN,NaN,NaN,34.75,140.625,7818.75,4886.71875

In [48]:
table_with_calc.loc[mask_wrong, 'sale_amt'] = (
    table_with_calc.loc[mask_wrong, 'total_calculation']
)
table_with_calc

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt,total_calculation
0,2018-01-06,East,Martha,Alexander,Television,95.00,1198.000,113810.00000,113810.00000
1,2018-01-23,Central,Hermann,Shelli,Home Theater,50.00,500.000,25000.00000,25000.00000
2,2018-02-09,Central,Hermann,Luis,Television,36.00,1198.000,43128.00000,43128.00000
3,2018-02-26,Central,Timothy,David,Cell Phone,27.00,225.000,6075.00000,6075.00000
4,2018-03-15,West,Timothy,Stephen,Television,56.00,1198.000,67088.00000,67088.00000
5,2018-04-01,East,Martha,Alexander,Home Theater,60.00,500.000,30000.00000,30000.00000
6,2018-04-18,Central,Martha,Steven,Television,75.00,1198.000,89850.00000,89850.00000
7,2018-05-05,Central,Hermann,Luis,Television,90.00,1198.000,107820.00000,107820.00000
8,2018-05-22,West,Douglas,Michael,Television,32.00,1198.000,38336.00000,38336.00000
9,2018-06-08,East,Martha,Alexander,Home Theater,60.00,500.000,30000.00000,30000.00000
10,2018-06-25,Central,Hermann,Sigal,Television,90.00,1198.000,107820.00000,107820.00000
11,2018-07-12,East,Martha,Diana,Home Theater,29.00,500.000,14500.00000,14500.00000
12,2018-07-29,East,Douglas,Karen,Home Theater,81.00,500.000,40500.00000,40500.00000
13,2018-08-15,East,Martha,Alexander,Television,35.00,1198.000,41930.00000,41930.00000
14,2018-09-01,Central,Douglas,John,Desk,2.00,125.000,250.00000,250.00000
15,2018-09-18,East,Martha,Alexander,Video Games,16.00,58.500,936.00000,936.00000
16,2018-10-05,Central,Hermann,Sigal,Home Theater,28.00,500.000,14000.00000,14000.00000
17,2018-10-22,East,Martha,Alexander,Cell Phone,64.00,225.000,14400.00000,14400.00000
18,2018-11-08,East,Douglas,Karen,Cell Phone,15.00,225.000,3375.00000,3375.00000
19,2018-11-25,Central,Hermann,Shelli,Video Games,96.00,58.500,5616.00000,5616.00000
20,2018-12-12,Central,Douglas,John,Television,67.00,1198.000,80266.00000,80266.00000
21,2018-12-29,East,Douglas,Karen,Video Games,74.00,58.500,4329.00000,4329.00000
22,2019-01-15,Central,Timothy,David,Home Theater,46.00,500.000,23000.00000,23000.00000
23,2019-02-01,Central,Douglas,John,Home Theater,87.00,500.000,43500.00000,43500.00000
24,2019-02-18,East,Martha,Alexander,Home Theater,4.00,500.000,2000.00000,2000.00000
25,2019-03-07,West,Timothy,Stephen,Home Theater,7.00,500.000,3500.00000,3500.00000
26,2019-03-24,Central,Hermann,Luis,Video Games,50.00,58.500,2925.00000,2925.00000
27,2019-04-10,Central,Martha,Steven,Television,66.00,1198.000,79068.00000,79068.00000
28,2019-04-27,East,Martha,Diana,Cell Phone,96.00,225.000,21600.00000,21600.00000
29,2019-05-14,Central,Timothy,David,Television,53.00,1198.000,63494.00000,63494.00000
30,2019-05-31,Central,Timothy,David,Home Theater,80.00,500.000,40000.00000,40000.00000
31,2019-06-17,Central,Hermann,Shelli,Desk,5.00,125.000,625.00000,625.00000
32,2019-07-04,East,Martha,Alexander,Video Games,62.00,58.500,3627.00000,3627.00000
33,2019-07-21,Central,Hermann,Sigal,Video Games,55.00,58.500,3217.50000,3217.50000
34,2019-08-07,Central,Hermann,Shelli,Video Games,42.00,58.500,2457.00000,2457.00000
35,2019-08-24,West,Timothy,Stephen,Desk,3.00,125.000,375.00000,375.00000
36,2019-09-10,Central,Timothy,David,Television,7.00,1198.000,8386.00000,8386.00000
37,2019-09-27,West,Timothy,Stephen,Cell Phone,76.00,225.000,17100.00000,17100.00000
38,2019-10-14,West,Douglas,Michael,Home Theater,57.00,500.000,28500.00000,28500.00000
39,2019-10-31,Central,Martha,Steven,Television,14.00,1198.000,16772.00000,16772.00000
40,2019-11-17,Central,Hermann,Luis,Home Theater,11.00,500.000,5500.00000,5500.00000
41,2019-12-04,Central,Hermann,Luis,Home Theater,94.00,500.000,47000.00000,47000.00000
42,2019-12-21,Central,Martha,Steven,Home Theater,28.00,500.000,14000.00000,14000.00000
43,NaN,NaN,NaN,NaN,NaN,278.00,1125.000,312750.00000,312750.00000
44,NaN,NaN,NaN,NaN,NaN,34.75,140.625,4886.71875,4886.71875